import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import ApppProvider from "./provider";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: [
    "200",
    "300",
    "400",
    "600",
    "700",
    "800",
    "900",
    "1000"
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased`}
      >
        <ApppProvider>
          { children }
        </ApppProvider>
      </body>
    </html>
  );
}
